# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Paul Samsotha
tagline:          'A Jekyll theme'
description:      "Paul Samsotha's developer blog"
url:              https://paulsamsotha.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Paul Samsotha'
  url:            https://github.com/psamsotha

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/psamsotha/paulsamsotha.com

urls:
  github:           https://github.com/psamsotha
  stackoverflow:    https://stackoverflow.com/users/2587435
  twitter:          https://twitter.com/PaulSamsotha
  facebook:         https://www.facebook.com/paul.samsotha
  googleplus:       https://plus.google.com/111592399635035486991  
